config/routes.rb
Cat::Application.routes.draw do
  devise_for :customers, :controllers => {:registrations => "customer_registrations", 
    :passwords => "customer_passwords" }

  namespace 'customer' do
    resources 'dashboard' , :only => [:index]
    resource 'profile', :only => [:show] do
      put :change_password
      put :change_username
    end
  end

  root :to => 'home#index'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	attr_accessible :auction_admin_id, :uid, :provider, :token
	belongs_to :auction_admin	
	
	def self.find_from_hash(hash)
		find_by_provider_and_uid(hash['provider'], hash['uid'])
	end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  PROFILE_ATTRIBUTES = [:email, :first_name, :last_name, :address, :city, :state, :zip_code, :country, :username]

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :confirmable, :authentication_keys => [:login]

  #Define attribute accessor
  attr_accessible :email, :password, :password_confirmation, :current_password, :remember_me, :first_name,
    :last_name, :username, :phone_number, :address, :city, :state, :zip_code, :country,
    :terms_of_service, :email_confirmation, :login
  attr_accessor :current_password, :login
  
  #Define validation
  validates :first_name, :presence => true, :format => { :with => /^[a-zA-Z ]+$/, :message => "Only letters allowed"  }
  validates :last_name, :presence => true, :format => { :with => /^[a-zA-Z ]+$/, :message => "Only letters allowed"  }
  validates :email, :presence => true, :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  validates :terms_of_service, :on => :create, :acceptance => true
  validates :username, :allow_blank => true, :uniqueness => true, :format => { :with => /^[\w]{4,}$/, :message => "should at-least contain 4 valid characters" }
  validates :phone_number, :format => { :with => /[+]{0,1}[\(\)\-0-9]*$/ }
  validates :city, :format => { :with => /^[a-zA-Z]*$/ , :message => "Only letters allowed" }
  validates :state, :format => {:with => /^[a-zA-Z]*$/, :message => "Only letters allowed"}
  validates :zip_code,  :format => { :with => /^[0-9]*$/ }
  validates :country, :format => { :with => /^[a-zA-Z ]*$/ , :message => "Only letters allowed" }

  #Define association
  belongs_to :parent, :class_name => 'Customer'
  has_many :children, :class_name => 'Customer'

  def is_profile_complete?
    @complete_attributes_count = 0
    PROFILE_ATTRIBUTES.each do |att|
      @complete_attributes_count += 1 if self[att].present?
    end
    @complete_attributes_count.to_i === PROFILE_ATTRIBUTES.size
  end

  def profile_complete_in_per
    return "100" if is_profile_complete? === true
    per = (@complete_attributes_count * 100) / PROFILE_ATTRIBUTES.size
    return per
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def after_sign_in_path_for(resource)
    if resource.is_a?(Customer)
      return customer_dashboard_index_path
    end
  end

  def after_update_path_for(resource)
    if resource.is_a?(Customer)
      return customer_dashboard_index_path
    end
  end

end

app/controllers/customer/base_controller.rb
class Customer::BaseController < ApplicationController
  layout "dashboard"
end

app/controllers/customer/dashboard_controller.rb
class Customer::DashboardController < Customer::BaseController
  before_filter :authenticate_customer!
  def index

  end
end

app/controllers/customer/profiles_controller.rb
class Customer::ProfilesController < Customer::BaseController
  before_filter :authenticate_customer!

  def show
    @customer = Customer.find(current_customer)
  end

  def change_password
    @resource = current_customer
    is_update = @resource.update_with_password(
      :password => params[:customer][:password],
      :password_confirmation => params[:customer][:password_confirmation], 
      :current_password => params[:customer][:current_password]
    )
    if is_update
      flash[:notice] = "Password updated successfully"
      sign_in @resource, :bypass => true
      redirect_to customer_dashboard_index_path
    end
  end

  def change_username
    @resource = current_customer
    is_update = @resource.update_without_password(:username => params[:customer][:username])
    if @resource.update_without_password(:username => params[:customer][:username])
      flash[:notice] = "Username updated successfully"
      sign_in @resource, :bypass => true
      redirect_to customer_dashboard_index_path
    end
  end
end

app/controllers/customer_passwords_controller.rb
class CustomerPasswordsController < Devise::PasswordsController
  
end

app/controllers/customer_registrations_controller.rb
class CustomerRegistrationsController < Devise::RegistrationsController
  before_filter :authenticate_customer!, :only => [:update, :edit]
  layout 'dashboard', :only => [:edit, :update]

  def update
    # required for settings form to submit when password is left blank
    @customer = current_customer
    if @customer.update_without_password(params[:customer])
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @customer, :bypass => true
      redirect_to customer_dashboard_index_path
    else
      render "edit_personal"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#before_filter :authenticate_auction_admin!
  
  def index
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def error_message(err_msg, classes)
    unless err_msg.blank?
      content_tag(:div, :class=> classes) do
        list_items = err_msg.map { |msg| content_tag(:li, msg) }
        content_tag(:ul, content_tag(:a,'&times'.html_safe, :class=>"close", 'data-dismiss'=>"alert") + list_items.join.html_safe, :class=>"set_err_msg" )
      end
    end
  end  
  
end

app/helpers/auction_admin/profile_helper.rb
module AuctionAdmin::ProfileHelper

  def resource_name
    :auction_admin
  end

  def resource
    @resource ||= AuctionAdmin.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:auction_admin]
  end

end

app/views/customer/dashboard/index.html.erb
<% content_for :header do %>
  <h1>Dashboard</h1>
     <div class='row'>
      <div class="span4"></div>
      <% if current_customer.is_profile_complete? %>
        <div class="span3" style="font-size:17px;">Profile Completeness(<%= current_customer.profile_complete_in_per %>%)</div>
        <div class="span2">
          <div class="progress progress-success">
            <div class="bar" style="width: <%= current_customer.profile_complete_in_per %>%;"></div>
          </div>
        </div>
      <% else %>
        <div class="span3 profile_box_completeness">Profile Completeness(<%= current_customer.profile_complete_in_per %>%)</div>
        <div class="span3 profile_box">
          <div class="span2">
            <span style="font-size:12px;">
              <%= link_to "Complete Your Profile", edit_customer_registration_path %>
            </span>
          </div>
          <div class="span2" style="width: 210px;">
            <div class="progress progress-success progress_bar_completeness">
              <div class="bar" style="width: <%= current_customer.profile_complete_in_per %>%;"></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
<% end %>

<% content_for :breadcrumb do %>
  <a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a>
  <a href="#" class="current">Dashboard</a>
<% end %>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title">
          <span class="icon"><i class="icon-file"></i></span>
          <h5>Recent Posts</h5>
          <span title="54 total posts" class="label label-info tip-left">54</span>
        </div>
    </div>
  </div>
  <div class="span6">
    <div class="widget-box">
      <div class="widget-title">
        <span class="icon"><i class="icon-comment"></i></span>
        <h5>Recent Comments</h5>
        <span title="88 total comments" class="label label-info tip-left">88</span>
      </div>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div id="footer" class="span12">
    @2013 &copy; Rachel
  </div>
</div>

app/views/customer/profiles/change_password.html.erb
<% content_for :header do %>
  <h1>Update Your Password</h1>
<% end %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span8">
      <%= render :partial => 'devise/registrations/change_password'%>
    </div>
  </div>
</div>

app/views/customer/profiles/change_username.html.erb
<% content_for :header do %>
  <h1>Update Your Username</h1>
<% end %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span8">
      <%= render :partial => 'devise/registrations/change_username'%>
    </div>
  </div>
</div>

app/views/customer/profiles/show.html.erb
<div id="content-header">
  <h1>Your Profile</h1>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="span1"></div>
    <div class="span7 offset1">
      <div class="widget-box">
        <div class="widget-title">
          <span class="icon">
            <i class="icon-user"></i>
          </span>
          <h5><%= @customer.full_name %></h5>
        </div>
        <div class="widget-content">
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">Username</span>
            </div>
            <div class="span2">
              <%= @customer.username %>
            </div>
          </div>
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">Email</span>
            </div>
            <div class="span2">
              <%= @customer.email %>
            </div>
          </div>
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">Phone Number</span>
            </div>
            <div class="span2">
              <%= @customer.phone_number %>
            </div>
          </div>
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">Address</span>
            </div>
            <div class="span2">
              <%= @customer.address %>
            </div>
          </div>
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">City/Town</span>
            </div>
            <div class="span2">
              <%= @customer.city %>
            </div>
          </div>
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">State/Province</span>
            </div>
            <div class="span2">
              <%= @customer.state %>
            </div>
          </div>
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">Zip Code</span>
            </div>
            <div class="span2">
              <%= @customer.zip_code%>
            </div>
          </div>
          <div class="row row-size margin_from_top">
            <div class="span2 offset1" style="text-align:left">
              <span style="font-weight:bold">Country</span>
            </div>
            <div class="span2">
              <%= @customer.country %>
            </div>
          </div>
        </div>
        <div class='span8 offset2'>
          <%= link_to 'Update Profile', edit_customer_registration_path, :class => 'btn btn-primary' %>  
          <%= link_to 'Back', customer_dashboard_index_path, :class => 'btn btn-inverse' %>  
        </div>
      </div>
    </div>
    <div class="span3"></div>
  </div>
</div>

app/views/home/index.html.erb
<div id="hero">
  <div class="container">
    <div class="row animated fadeInDown">
      <div class="span12">
        <div id="myCarousel" class="carousel slide" style="min-height :285px;">
          <div class="carousel-inner">
           <div class="active item slide1">
              <div class="row">
                <div class="span6 offset3">
                  <h1>
                    Responsive and Clean rachel.loantracx.com
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- starts footer -->
<div id="footer" style="min-height: 50px; padding-top: 0;">
  <div class="container">
    <div class="row copyright">
      <div class="span5">
        <h3>Social</h3>
        <a href="#" class="social fb" target="_blank">
          <i class="i_facebook"></i>
        </a>
        <a href="#" class="social tw" target="_blank">
          <i class="i_twitter"></i>
        </a>
        <a href="#" class="social yt">
          <i class="i_youtube"></i>
        </a>
      </div>
      <div class="span3 offset4 copy">
        <p>@2013 -rachel.loantracx.com</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <h1 class="logo_fix">
    <%= link_to "CAT Admin", customer_dashboard_index_path %>
  </h1>
</div>

<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav btn-group">
    <li class="btn btn-inverse" >
      <%= link_to '<i class="icon icon-home"></i> <span class="text">Home</span>'.html_safe, root_path %>
    </li>

    <li class="btn btn-inverse" >
      <%= link_to '<i class="icon icon-user"></i> <span class="text">Profile</span>'.html_safe, customer_profile_path %>
    </li>
    <li class="btn btn-inverse">
      <a title="" href="<%= edit_customer_registration_path %>">
        <i class="icon icon-cog"></i>
        <span class="text">Settings</span>
      </a>
    </li>
    <li class="btn btn-inverse">
      <%= link_to '<i class="icon icon-share-alt"></i><span class="text">Logout</span>'.html_safe, destroy_customer_session_path, :method => :delete %>
    </li>
  </ul>
</div>

<div id="sidebar">
  <a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
  <ul>
    <li class="active">
      <%= link_to '<i class="icon icon-home"></i><span>Dashboard</span>'.html_safe, customer_dashboard_index_path %>
    </li>
  </ul>
</div>

app/views/layouts/_home_header.html.erb
<a href="#" class="scrolltop">
  <span>up</span>
</a>

<!-- begins navbar -->
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <% if current_customer %>                                    
            <li><%= link_to('Dashboard', customer_dashboard_index_path) %></li>                
            <li><%= link_to('Sign out', destroy_customer_session_path, :class=>"btn-header", :method => :delete) %></li>
          <% else %>
            <li><%= link_to('Sign up', new_customer_registration_path, :class=>"btn-header") %></li>                
            <li><%= link_to('Sign in', new_customer_session_path, :class=>"btn-header") %></li>                
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- ends navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loan</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "frontend_application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "layouts/home_header" %>
  <div class="flash row margin-auto">
    <div class="flash_message">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= yield%>
  <%= render :partial => "layouts/footer" %>
  <%= javascript_include_tag "frontend_application" %>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "dashboard_application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render :partial => "layouts/header" %>
    <div id="content">
      <div id="content-header">
        <%= yield :header %>
      </div>
      <div id="breadcrumb">
        <%= yield :breadcrumb %>
      </div>
      <div class="flash row margin-auto">
        <div class="aution_flash_message">
          <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>

    <%= javascript_include_tag "dashboard_application" %>
  </body>
</html>

app/views/pages/aboutus.html.erb
<!-- features -->
<div id="about" class="about_page">
    <div class="container">
        <!-- header -->
        <h2 class="section_header">
            <hr class="left visible-desktop">
            <span>About Us</span>
            <hr class="right visible-desktop">
        </h2>

        <div class="row">
            <div class="span12">
                <h3 class="intro">
                    Whether you need to create a brand from scratch, including marketing materials
                    and a beautiful and functional website or whether you are looking for a design
                    refresh pleased with the results.
                </h3>
            </div>
        </div>

        <!-- description -->
        <div class="row">
            <div class="span6">
                <p>
                    here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which <br>
                    don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, <br>
                    you need to be sure there isn't anything embarrassing hidden in the middle of text. <br>
                    All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.
                    here are many variations of passages of Lorem Ipsum available, but the <br> majority have suffered alteration in some form, by injected humour, or randomised <br> words which 
                    don't look even slightly believable. If you are going to use a passage of <br> Lorem Ipsum.
                </p>
            </div>
            <div class="span6">
                <p>
                    here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which <br>
                    don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, <br>
                    you need to be sure there isn't anything embarrassing hidden in the middle of text. <br>
                    All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.
                    here are many variations of passages of Lorem Ipsum available, but the <br> majority have suffered alteration in some form, by injected humour, or randomised <br> words which 
                    don't look even slightly believable. If you are going to use a passage of <br> Lorem Ipsum.
                </p>
            </div>
        </div>

        <!-- header -->
        <h2 class="section_header team">
            <hr class="left visible-desktop">
            <span>Our Team</span>
            <hr class="right visible-desktop">
        </h2>

        <div class="row">
            <div class="span3 teammate">
                <img src="/assets/about.png" class="" />
                <h5>Alejandra Galván Castillo</h5>
                <p>Creative Director</p>
                <hr>
                <p class="description">
                    We are a fairly small, flexible design studio that designs for the web.
                    We work with clients to fulfill their
                    needs.
                </p>
                <div class="social">
                    <a href="#">
                        <i class="social tw"></i>
                    </a>
                    <a href="#">
                        <i class="social fb"></i>
                    </a>
                    <a href="#">
                        <i class="social gp"></i>
                    </a>
                    <a href="#">
                        <i class="social pin"></i>
                    </a>
                </div>
            </div>
            <div class="span3 teammate">
                <img src="/assets/about.png" class="" />
                <h5>Alejandra Galván Castillo</h5>
                <p>Creative Director</p>
                <hr>
                <p class="description">
                    We are a fairly small, flexible design studio that designs for the web.
                    We work with clients to fulfill their
                    needs.
                </p>
                <div class="social">
                    <a href="#">
                        <i class="social tw"></i>
                    </a>
                    <a href="#">
                        <i class="social fb"></i>
                    </a>
                    <a href="#">
                        <i class="social gp"></i>
                    </a>
                </div>
            </div>
            <div class="span3 teammate">
                <img src="/assets/about.png" class="" />
                <h5>Alejandra Galván Castillo</h5>
                <p>Creative Director</p>
                <hr>
                <p class="description">
                    We are a fairly small, flexible design studio that designs for the web.
                    We work with clients to fulfill their
                    needs.
                </p>
                <div class="social">
                    <a href="#">
                        <i class="social tw"></i>
                    </a>
                    <a href="#">
                        <i class="social fb"></i>
                    </a>
                    <a href="#">
                        <i class="social gp"></i>
                    </a>
                </div>
            </div>
            <div class="span3 teammate">
                <img src="/assets/about.png" class="" />
                <h5>Alejandra Galván Castillo</h5>
                <p>Creative Director</p>
                <hr>
                <p class="description">
                    We are a fairly small, flexible design studio that designs for the web.
                    We work with clients to fulfill their
                    needs.
                </p>
                <div class="social">
                    <a href="#">
                        <i class="social tw"></i>
                    </a>
                    <a href="#">
                        <i class="social fb"></i>
                    </a>
                    <a href="#">
                        <i class="social gp"></i>
                    </a>
                    <a href="#">
                        <i class="social pin"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/coming_soon.html.erb
    <!-- coming soon -->
    <div id="comingsoon" class="comingsoon_page">
        <div class="container">
            <div class="countdown">
              <div class="row">
                  <div class="span6 offset1 left">
                    <h1>We are launching very soon...</h1>
                    <p>
                      There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.
                    </p>
                  </div>
                  <div class="span5 right">
                    <div class="figure">
                      <div class="square">
                        <span>165</span>
                      </div>
                      <label>DAYS</label>
                    </div>
                    <div class="figure">
                      <div class="square">
                        <span>75</span>
                      </div>
                      <label>HOURS</label>
                    </div>
                    <div class="figure">
                      <div class="square">
                        <span>34</span>
                      </div>
                      <label>MINUTES</label>
                    </div>
                    <div class="figure">
                      <div class="square">
                        <span>22</span>
                      </div>
                      <label>SECONDS</label>
                    </div>
                  </div>
              </div>
            </div>
            <div class="subscribe">
              <div class="row">
                <div class="span12">
                  <form>
                    <input type="text" class="span4" placeholder="Email address" />
                    <button type="submit" class="btn">Subscribe</button>
                  </form>
                  <div class="follow">
                    <strong>Follow us</strong>
                    <a href="#">
                      <i class="social tw"></i>
                    </a>
                    <a href="#">
                      <i class="social fb"></i>
                    </a>
                    <a href="#">
                      <i class="social pin"></i>
                    </a>
                    <a href="#">
                      <i class="social in"></i>
                    </a>
                    <a href="#">
                      <i class="social gp"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>

app/views/pages/pricing.html.erb
<!-- starts pricing -->
<div id="pricing" class="pricing_page">
  <div class="container">
    <h2 class="section_header">
      <hr class="left visible-desktop">
        <span>
          Pricing 
          <small>
          See all plan details here</small>
        </span>
      <hr class="right visible-desktop">
    </h2>
<!-- pricing charts 1 -->
<div class="row">
    <div class="span4">
        <div class="price_wrapper lite regular">
            <div class="header">
                <span>Lite</span>
                <div class="price">
                    <span>$ 35</span>
                    Per Month
                </div>
            </div>
            <div class="section">
                <h3>Passages of Lorem randomised
                    words which look slightly.</h3>
                <ul class="perks">
                    <li>
                        <i class="i_shuffle"></i>
                        Cross-browser
                    </li>
                    <li>
                        <i class="i_loading"></i>
                        Fast-loading
                    </li>
                </ul>
                <a href="#" class="btn">Order now</a>
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="price_wrapper pro">
            <div class="header">
                <span>Pro</span>
                <div class="price">
                    <span>$ 99</span>
                    Per Month
                </div>
            </div>
            <div class="section">
                <h3>Passages of Lorem randomised
                    words which look slightly.</h3>
                <ul class="perks">
                    <li>
                        <i class="i_shuffle"></i>
                        Cross-browser
                    </li>
                    <li>
                        <i class="i_loading"></i>
                        Fast-loading
                    </li>
                    <li>
                        <i class="i_bookmark"></i>
                        Bookmarkable URLs
                    </li>
                    <li>
                        <i class="i_bars"></i>
                        W3C Standards
                    </li>
                </ul>
                <a href="#" class="btn">Order now</a>
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="price_wrapper standard regular">
            <div class="header">
                <span>Standard</span>
                <div class="price">
                    <span>$ 65</span>
                    Per Month
                </div>
            </div>
            <div class="section">
                <h3>Passages of Lorem randomised
                    words which look slightly.</h3>
                <ul class="perks">
                    <li>
                        <i class="i_shuffle"></i>
                        Cross-browser
                    </li>
                    <li>
                        <i class="i_loading"></i>
                        Fast-loading
                    </li>
                    <li>
                        <i class="i_bookmark"></i>
                        Bookmarkable URLs
                    </li>
                </ul>
                <a href="#" class="btn">Order now</a>
            </div>
        </div>
    </div>
</div>

app/views/shared/_left_side_menu.html.erb
<li class="nav-header">List header</li>
<li class="nav-header"></li>
<li><%= link_to('Home', root_path, :class=>"navbar-link") %></li>
<li><%= link_to('Sign In', new_auction_admin_session_path, :class=>"navbar-link") %></li>
<li><%= link_to('Sign Up', new_auction_admin_registration_path, :class=>"navbar-link") %></li>

<% if !current_auction_admin %>
  <div class="omniauth-connect">
    <h4>Sign in with</h4>
    <% ["Facebook"].each do |provider| %>
      <li><%= link_to "#{provider}", "/auth/#{provider}" %></li>
    <% end %>
    <h4><%= link_to 'Back', new_session_url if params[:controller] == 'users' %></h4>
  </div>
<% end %>